Brisanet/ion

.github/workflows/main.yml, README.md, tsconfig.json
=> ci: add codeclimate report to coverage monitor

projects/ion/src/styles/themes/index.scss
=> style: add spacing #51

projects/ion/src/lib/divider/divider.component.html, projects/ion/src/lib/divider/divider.component.scss, projects/ion/src/lib/divider/divider.component.spec.ts, projects/ion/src/lib/divider/divider.component.ts, projects/ion/src/lib/ion.module.ts, stories/Divider.stories.mdx
[x] Feature
- O que está PR faz?
Criação do componente divider do design-systems, com as seguintes propriedades:
1.  Orientação: dado pelo atributo `orientation`, que recebe apenas dois valores, `vertical` e `horizontal`. Sendo `horizontal` o valor padrão.
2. Tipo: dado pelo atributo `type`, que recebe os valores: `text`, `solid`, `dashed`. Sendo `solid` o valor padrão.
3. Label: dado pelo atributo `label`. Apenas será utilizada caso `type` seja igual a `text`.
=> feat: issue #50 divider component

projects/ion/src/lib/tab/tab.component.html, projects/ion/src/lib/tab/tab.component.scss, projects/ion/src/lib/tab/tab.component.spec.ts, projects/ion/src/lib/tab/tab.component.ts, stories/Tab.stories.ts
=> feat: icon in tab #47

.github/workflows/chromatic.yml, .github/workflows/main.yml, .github/workflows/prod.yml, projects/ion/src/lib/core/types/direction.ts, projects/ion/src/lib/core/types/index.ts, projects/ion/src/lib/divider/divider.component.html, projects/ion/src/lib/divider/divider.component.spec.ts, projects/ion/src/lib/divider/divider.component.ts, stories/Divider.stories.mdx
=> Add DirectionType in divider

projects/ion/src/lib/tab-group/tab-group.component.html, projects/ion/src/lib/tab-group/tab-group.component.scss, projects/ion/src/lib/tab-group/tab-group.component.spec.ts, projects/ion/src/lib/tab-group/tab-group.component.ts, projects/ion/src/lib/tab/tab.component.scss, stories/TabGroup.stories.ts
=> feat: support icon in tab group #68

projects/ion/src/lib/core/types/index.ts, projects/ion/src/lib/core/types/status.ts
=> feat: add new type to status #78

projects/ion/src/lib/icon/icon.component.html, projects/ion/src/lib/icon/icon.component.scss, projects/ion/src/lib/icon/icon.component.ts
=> 🚑  Fix icon size and render binded #95

projects/ion/src/lib/chip/chip.component.spec.ts, projects/ion/src/lib/chip/chip.component.ts
fix #100 
Add event when click in chip
=> ✨ Add event in chip

projects/ion/src/lib/card/card.component.html, projects/ion/src/lib/card/card.component.scss, stories/Card.stories.mdx
=> fix: layout card header 🎨  #113

projects/ion/src/lib/button/button.component.spec.ts, projects/ion/src/lib/button/button.component.ts
=> 🚑  shouldnt emit the event when click in disabled button

projects/ion/src/lib/ion.module.ts
Fixing an issue(Unexpected value 'undefined' exported by the module) that appeared in the supplychain build.
=> fix: correcting barrel import

projects/ion/src/lib/tab-group/tab-group.component.html, projects/ion/src/lib/tab-group/tab-group.component.spec.ts, projects/ion/src/lib/tab-group/tab-group.component.ts, projects/ion/src/lib/tab/tab.component.ts, stories/TabGroup.stories.ts
=> feat: add different sizes in tabgroup #133 :art:

projects/ion/src/lib/tab/tab.component.scss
fix focus problem in tab group
=> fix: focus problem (#124)

projects/ion/src/lib/message/message.component.ts
=> feat: add icon type in message(#156) :sparkles:

README.md, projects/ion/src/lib/chip/chip.component.html, projects/ion/src/lib/chip/chip.component.spec.ts, projects/ion/src/lib/chip/chip.component.ts, projects/ion/src/public-api.ts, stories/Chip.stories.ts
=> :sparkles: add info badge in chip #147

projects/ion/src/lib/card/card.component.scss
=> Fix header spacing

projects/ion/src/lib/chip/chip.component.scss
=> Change add-colors in chip desabled

projects/ion/src/lib/chip/chip.component.scss
=> Change icon-color chip desable

projects/ion/src/lib/chip/chip.component.scss
=> fix: disabled chip color adjustment (#195)

projects/ion/src/lib/notification/notification.component.html, projects/ion/src/lib/notification/notification.component.scss
=> fix: notification height correction (#194)

projects/ion/src/lib/chip/chip.component.html, projects/ion/src/lib/chip/chip.component.spec.ts, projects/ion/src/lib/chip/chip.component.ts, stories/Chip.stories.ts
=> ✨  badge in right side of chip

.github/workflows/chromatic.yml, projects/ion/src/lib/button/button.component.html, projects/ion/src/lib/button/button.component.spec.ts, projects/ion/src/lib/button/button.component.ts, stories/Button.stories.mdx
=> refactor: remove default msg when button is loading :hammer: #281

projects/ion/src/lib/checkbox/checkbox.component.spec.ts, projects/ion/src/lib/checkbox/checkbox.component.ts
=> fix: missed event of checkbox :ambulance: #291

projects/ion/src/lib/alert/alert.component.scss, projects/ion/src/lib/button/button.component.scss, projects/ion/src/lib/checkbox/checkbox.component.scss, projects/ion/src/lib/chip/chip.component.scss, projects/ion/src/lib/date-picker/date-picker/date-picker.component.scss, projects/ion/src/lib/dropdown/dropdown.component.scss, projects/ion/src/lib/info-badge/info-badge.component.scss, projects/ion/src/lib/pagination/pagination.component.scss, projects/ion/src/lib/radio/radio.component.scss, projects/ion/src/lib/tab/tab.component.scss, projects/ion/src/lib/table/table.component.scss
=> refactor: changing primary 6 to primary color(#167)

projects/ion/src/lib/chip/chip.component.html, projects/ion/src/lib/chip/chip.component.spec.ts, projects/ion/src/lib/chip/chip.component.ts, projects/ion/src/lib/dropdown/dropdown.component.ts
=> ✨ Add event to chip when select a option in dropdown :sparkles: #300

projects/ion/src/lib/button/button.module.ts, projects/ion/src/lib/card/card.component.spec.ts, projects/ion/src/lib/date-picker/date-picker/date-picker.component.spec.ts, projects/ion/src/lib/input-counter/input-counter.component.spec.ts, projects/ion/src/lib/modal/component/modal.component.spec.ts, projects/ion/src/lib/modal/modal.service.spec.ts, projects/ion/src/lib/pagination/pagination.component.spec.ts, projects/ion/src/lib/simple-menu/simple-menu.component.spec.ts, projects/ion/src/lib/smart-table/smart-table.component.spec.ts, projects/ion/src/lib/table/table.component.spec.ts, stories/Card.stories.mdx, stories/Datepicker.stories.ts, stories/InputCounter.stories.ts, stories/Modal.stories.mdx, stories/Modal.stories.ts, stories/Pagination.stories.ts, stories/SimpleMenu.stories.ts, stories/SmartTable.stories.ts, stories/Table.stories.ts
=> ✨ Create button module

projects/ion/src/lib/popconfirm/popconfirm.directive.spec.ts, projects/ion/src/lib/popconfirm/popconfirm.directive.ts
=> ✨ Close popconfirm when click in confirm button :sparkles: #306

projects/ion/src/lib/divider/divider.component.html, projects/ion/src/lib/divider/divider.component.ts
:face_in_clouds: 
[Gravação de tela de 25-11-2022 09:25:46.webm](https://user-images.githubusercontent.com/8728782/203985737-78e23637-ce3a-4d0e-9286-1a6451055bd9.webm)
=> fix: added configuration

projects/ion/src/lib/smart-table/smart-table.component.html, projects/ion/src/lib/smart-table/smart-table.component.spec.ts, stories/SmartTable.stories.ts
=> fix: remove order button when order is false #340 :ambulance:

projects/ion/src/lib/input/input.component.scss
=> style: fix line height of input

projects/ion/src/lib/input/input.component.scss, projects/ion/src/lib/smart-table/smart-table.component.spec.ts, projects/ion/src/lib/smart-table/smart-table.component.ts, projects/ion/src/lib/table/utilsTable.ts
=> Fix table order 361

projects/ion/src/lib/card/card.component.html, projects/ion/src/lib/card/card.component.scss, projects/ion/src/lib/card/card.component.ts, projects/ion/src/lib/card/mock/body-mock.component.ts, stories/Card.stories.mdx
Check #379 for more details on this one.
=> fix: rendering issues on card component when body is empty

projects/ion/src/lib/smart-table/smart-table.component.spec.ts, projects/ion/src/lib/smart-table/smart-table.component.ts
=> fix: order property undefined #374 :ambulance:

projects/ion/src/lib/input/input.component.spec.ts
=> remove duplicate tests in input

projects/ion/src/lib/button/button.component.html, projects/ion/src/lib/pagination/pagination.component.spec.ts
- changes the button identification attribute to facilitate testing with jest
- change in pagination test due to change in button id attribute
- to facilitate button tests
To find the button in jest can use <code> screen.getByTestId(\`btn-${label}\`)) </code> or <code>screen.findByTestId(\`btn-${label}\`)</code>
=> test: changing identify attribute of button

projects/ion/src/lib/button/button.component.html, projects/ion/src/lib/modal/component/modal.component.html
When I trynna build the models at Supply Chain system, occurred an error because the HTML code from this two components are trying access variable that maybe undefined. So, to fix it, will be necessary add '?' point marks at:
- Button Component: rows 33 and 34 from HTML.
- Modal Component: rows 35 and 36 from HTML.
=> fix: adjustment at variable calls from button and modal components

.github/workflows/main.yml
=> fix: pipeline to forks :ambulance:

.github/workflows/chromatic.yml
=> fix: add target

projects/ion/src/lib/core/types/index.ts, projects/ion/src/lib/core/types/radio-group.ts, projects/ion/src/lib/ion.module.ts, projects/ion/src/lib/radio-group/radio-group.component.html, projects/ion/src/lib/radio-group/radio-group.component.scss, projects/ion/src/lib/radio-group/radio-group.component.spec.ts, projects/ion/src/lib/radio-group/radio-group.component.ts, projects/ion/src/lib/radio-group/radio-group.module.ts, projects/ion/src/public-api.ts, stories/Radio.stories.ts, stories/RadioGroup.stories.ts
[Screencast from 28-02-2023 09:45:04.webm](https://user-images.githubusercontent.com/57760325/221863257-3c29b3a2-cd4a-43e4-bb8f-10ebc2e44c03.webm)
=> ✨ feat: radio group

projects/ion/src/lib/tooltip/tooltip.component.scss
=> style: change fontsize, align and padding of tooltip :art: #492

projects/ion/src/lib/core/types/index.ts, projects/ion/src/lib/core/types/switch.ts, projects/ion/src/lib/switch/switch.component.html, projects/ion/src/lib/switch/switch.component.scss, projects/ion/src/lib/switch/switch.component.spec.ts, projects/ion/src/lib/switch/switch.component.ts
- Add new size options to switch (#496)
- Change colors and add a disable option to switch (#502)
=> feat: sizes on switch component

projects/ion/package.json
update version ion for v0.0.44
=> build: update version ion for v0.0.44

projects/ion/package.json
update version ion for v0.0.45
=> build: update version ion for v0.0.45

projects/ion/src/lib/chip/chip.component.spec.ts, projects/ion/src/lib/popconfirm/popconfirm.directive.spec.ts, projects/ion/src/lib/popover/popover.directive.spec.ts
This pull request is created to add additional tests for the popconfirm and popover components of the Ion Designer System. The objective of this change is to increase the coverage in these components and ensure that they are thoroughly tested.
Modified files in this pull request include "popconfirm.spec.ts" and "popover.spec.ts". Changes made to these files involve the addition of new test cases and modifications to existing test cases.
=> test: creating tests de element duplicate and element disabled

projects/ion/src/lib/ion.module.ts, projects/ion/src/lib/spinner/spinner.component.html, projects/ion/src/lib/spinner/spinner.component.scss, projects/ion/src/lib/spinner/spinner.component.ts, projects/ion/src/lib/spinner/spinner.componet.spec.ts, projects/ion/src/lib/spinner/spinner.module.ts, projects/ion/src/public-api.ts, stories/spinner.stories.ts
This PR adds the ion-spinner component, the ion-spinner can be used to indicate loading or progress in different parts of the application and can be styled to suit the application's design. ion-spinner is easy to use and can be added to any page or component. This feature enhances the user experience and provides visual feedback for long running operations.
- Feature ion-spinner
=> feat: spinner component creation

projects/ion/src/lib/notification/notification.component.scss
Now the notification width have a fixed size of 500px.
=> feat: adding max width (#560)

projects/ion/package.json, projects/ion/src/lib/ion.module.ts, projects/ion/src/lib/smart-table/smart-table.component.html, projects/ion/src/lib/smart-table/smart-table.component.spec.ts, projects/ion/src/lib/smart-table/smart-table.module.ts, projects/ion/src/lib/utils/pipes/pipes.module.ts, projects/ion/src/lib/utils/pipes/replace-empty/index.ts, projects/ion/src/lib/utils/pipes/replace-empty/replace-empty.pipe.spec.ts, projects/ion/src/lib/utils/pipes/replace-empty/replace-empty.pipe.ts
must add a (-) when there is no data in the cell
=> feat: add (-) when there is no data in the cell

projects/ion/src/lib/popconfirm/popconfirm.component.html, projects/ion/src/lib/popconfirm/popconfirm.component.scss, projects/ion/src/lib/popconfirm/popconfirm.directive.spec.ts, projects/ion/src/lib/popconfirm/popconfirm.directive.ts
fix #535 
opened by #579 
* fix: popconfirm appears in left or right visible area (#535)
* refactor: adjusting functions and their params (#535)
* test: first test setup to new config (#535)
* test: testing the popconfirm position when it opens(#535)
=> 535 fix popconfirm to appear in visible area (#579)

projects/ion/src/lib/message/message.component.scss
Now the size adapts to the content.
=> feat: size adapt to content (#559)

projects/ion/package.json
=> build: v0.0.52

projects/ion/src/lib/pagination/pagination.component.html, projects/ion/src/lib/pagination/pagination.component.scss, projects/ion/src/lib/smart-table/smart-table.component.html, projects/ion/src/lib/table/table.component.scss, stories/SmartTable.stories.ts
fix #606 
Storybook: https://62eab350a45bdb0a5818520e-sxcfomeijj.chromatic.com/
=> fix: select data per page and improve style of pagination

README.md, projects/ion/src/lib/breadcrumb/breadcrumb.component.scss, projects/ion/src/lib/button/button.component.spec.ts, projects/ion/src/lib/dropdown/dropdown.component.html, projects/ion/src/lib/dropdown/dropdown.component.scss
Added scroll in dropdown options, now clear button and search keep on bottom and top.
Storybook 📝 : https://62eab350a45bdb0a5818520e-mbkbwkepda.chromatic.com/
=> fix: scroll in dropdown component :ambulance:

projects/ion/src/lib/chip/chip.component.spec.ts, projects/ion/src/lib/chip/chip.component.ts
=> dispatch event in chip when clear options on dropdown ✨ 

projects/ion/src/lib/popconfirm/popconfirm.directive.ts
=> fix: popconfirm error directive when clicked again #616 :ambulance:

projects/ion/src/lib/core/types/pagination.ts, projects/ion/src/lib/pagination/pagination.component.spec.ts, projects/ion/src/lib/pagination/pagination.component.ts, projects/ion/src/lib/smart-table/smart-table.component.html, projects/ion/src/lib/smart-table/smart-table.component.ts, projects/ion/src/lib/table/table.component.html, projects/ion/src/lib/table/table.component.ts, projects/ion/src/lib/table/utilsTable.ts, stories/Pagination.stories.ts, stories/SmartTable.stories.ts
#621 
[Storybook](https://62eab350a45bdb0a5818520e-rwapnysvga.chromatic.com/?path=/story/ion-data-display-smarttable--custom-page-size-options)
=> feat: custom page size options on pagination

projects/ion/package.json
=> chore: new version

projects/ion/src/lib/smart-table/smart-table.component.html, projects/ion/src/lib/smart-table/smart-table.component.spec.ts, projects/ion/src/lib/smart-table/smart-table.component.ts, projects/ion/src/lib/table/table.component.html, projects/ion/src/lib/table/table.component.scss, projects/ion/src/lib/table/table.component.spec.ts, projects/ion/src/lib/table/table.component.ts, projects/ion/src/lib/table/utilsTable.ts, stories/SmartTable.stories.ts
Basically, the show/hide behavior was added and the old show behavior was moved to disabled.
=> Implementing the show for table actions and moving show behavior to disabled

projects/ion/src/lib/modal/component/modal.component.scss
=> fix: fixed overlay of the modal

projects/ion/src/lib/popconfirm/popconfirm.directive.spec.ts, projects/ion/src/lib/popconfirm/popconfirm.directive.ts
fix #663
https://62eab350a45bdb0a5818520e-nkmfhkxswy.chromatic.com/
=> 663 fix popconfirm is opening with a disabled button

projects/ion/src/lib/button/button.component.html, projects/ion/src/lib/button/button.component.spec.ts, projects/ion/src/lib/button/button.component.ts, projects/ion/src/lib/click-outside.directive.ts, projects/ion/src/lib/dropdown/dropdown.component.html, projects/ion/src/lib/dropdown/dropdown.component.ts, projects/ion/src/lib/shared.module.ts
=> feat: create a new directive to emit event when click component outside

projects/ion/src/lib/button/button.component.html, projects/ion/src/lib/button/button.component.ts, projects/ion/src/lib/core/types/dropdown.ts, projects/ion/src/lib/dropdown/dropdown.component.ts, projects/ion/src/lib/pagination/pagination.component.html
fix #673 
→ View your Storybook at https://62eab350a45bdb0a5818520e-greiewexqx.chromatic.com/
=> feat: remove clear button from pagination selector #673 :sparkles:

projects/ion/src/lib/table/table.component.scss
=> fix: add words break at cells from table

projects/ion/src/lib/step/step.component.html, projects/ion/src/lib/step/step.component.scss
fix #680 
→ View your Storybook at https://62eab350a45bdb0a5818520e-expmnjsrhg.chromatic.com/
=> fix: alignment at step component

projects/ion/src/lib/modal/component/modal.component.scss
=> feat: change scroll color on modal

projects/ion/src/lib/smart-table/smart-table.component.html, projects/ion/src/lib/smart-table/smart-table.component.spec.ts, projects/ion/src/lib/smart-table/smart-table.module.ts, stories/SmartTable.stories.ts
=> ✨ add loading in table content when table is loading and dont have data

projects/ion/src/lib/pagination/pagination.component.ts
@AlyssonMascarenhas 
This is fix pagination when change the total de page and mode advanced not is changed
=> fix: pagination advanced :ambulance:

projects/ion/package.json, projects/ion/src/public-api.ts, stories/SmartTable.stories.ts
=> feat: export skeleton and new build 0.0.65

projects/ion/package.json
fix #721 
This change link npm with github repo
=> 721 improve npm publish package via GitHub token

projects/ion/src/lib/click-outside.directive.ts, projects/ion/src/lib/modal/modal.service.ts
=> fix: validation of hostView when modal is closing

projects/ion/package.json
=> feat: update version

projects/ion/src/lib/pagination/pagination.component.spec.ts, projects/ion/src/lib/pagination/pagination.component.ts
fix #761 
Change on the array with the new default values for the itemsPerPage
Run yarn test pagination
=> feat: items per page default value change and tests adjustments

projects/ion/src/lib/table/table.component.html, projects/ion/src/lib/table/table.component.spec.ts, projects/ion/src/lib/table/table.component.ts, stories/Table.stories.ts
fixing some bugs in table reported by @mizek1
=> Table change fix

projects/ion/src/lib/popover/component/popover.component.html, projects/ion/src/lib/popover/component/popover.component.scss, projects/ion/src/lib/popover/component/popover.component.spec.ts, projects/ion/src/lib/popover/component/popover.component.ts
=> Feat popover custom class

projects/ion/src/lib/core/types/smart-table.ts, projects/ion/src/lib/core/types/tooltip.ts, projects/ion/src/lib/smart-table/smart-table.component.html, projects/ion/src/lib/smart-table/smart-table.component.spec.ts, projects/ion/src/lib/smart-table/smart-table.component.ts, projects/ion/src/lib/table/utilsTable.ts, stories/SmartTable.stories.ts
fix #771 
Changes on the types to allow multiple tooltip configs
- Removed the tooltipConfig from the smart-table config to the actions interface;
- adjusted the html file with the correct property binding path;
- adjusted the tests and storybook files;
Run yarn test smart-table or check the smart table stories
[Storybook](https://62eab350a45bdb0a5818520e-mjsghdcbmd.chromatic.com/)
=> fix: tooltip in action buttons adjustments

projects/ion/src/lib/core/types/simple-menu.ts, projects/ion/src/lib/simple-menu/simple-menu.component.html, projects/ion/src/lib/simple-menu/simple-menu.component.scss, projects/ion/src/lib/simple-menu/simple-menu.component.spec.ts, projects/ion/src/lib/simple-menu/simple-menu.component.ts, stories/SimpleMenu.stories.ts
feat #774 
Insert logo in Simple Menu
- insert a Input for logo
=> feat: insert logo in simple menu

projects/ion/src/lib/picker/control-picker/control-picker.component.html, projects/ion/src/lib/picker/control-picker/control-picker.component.spec.ts
fix #785 
Change of the button click event listener to ionOnClick and test adjusments.
=> fix: ion button click event on control-picker and test adjusments

projects/ion/src/lib/pagination/pagination.component.html, projects/ion/src/lib/pagination/pagination.component.spec.ts, projects/ion/src/lib/pagination/pagination.component.ts
fix #784 
Change of the button click event listener to ionOnClick and test adjusments.
=> fix: ion button click event on pagination and test adjusments

projects/ion/src/lib/modal/component/modal.component.html
fix #783 
Change of the button click event listener to ionOnClick.
=> fix: ion button click event on modal

projects/ion/src/lib/picker/control-picker/control-picker.component.spec.ts
Changed the click event to the button within the ion-button
=> refactor: control-picker test adjustment

projects/ion/src/lib/popover/popover.directive.ts, stories/Popover.stories.ts
Popover icon color was not changing because the property was not added to the directive file.
=> fix: popover icon color added to directive

projects/ion/src/core/bn-table/bn-table.spec.ts, projects/ion/src/core/bn-table/bn-table.ts, projects/ion/src/lib/table/utilsTable.ts
=> feat: add refresh filter to bn-filter on bn-table #812

projects/ion/src/core/api/http.interfaces.ts, projects/ion/src/core/bn-table/bn-table.ts
=> [core] feat: add get method to bnService :sparkles: #803

projects/ion/src/lib/core/types/popover.ts, projects/ion/src/lib/popover/popover.directive.spec.ts, projects/ion/src/lib/popover/popover.directive.ts, stories/Popover.stories.ts
feat #815 
Inset directive ionPopoverCustomClass
=> feat: insert directive ionPopoverCustomClass

projects/ion/src/core/bn-table/bn-table.spec.ts, projects/ion/src/core/bn-table/bn-table.ts, projects/ion/src/lib/use-table/use-table.component.ts
fix #823 
reported @PedroMiguel7
=> feat: add default order on bntable #823

projects/ion/src/lib/table/table.component.html, projects/ion/src/lib/table/table.component.spec.ts, projects/ion/src/lib/table/table.module.ts
fix #820 
Loading added to ion-table
yarn test table
[storybook](https://62eab350a45bdb0a5818520e-kzxuururgz.chromatic.com/?path=/story/ion-data-display-table--basic)
=> fix: loading on ion-table

projects/ion/src/lib/smart-table/smart-table.component.html, projects/ion/src/lib/smart-table/smart-table.component.spec.ts, projects/ion/src/lib/table/table.component.html, projects/ion/src/lib/table/table.component.spec.ts
fix #826
Fix in logic to disable action buttons in ion-table and ion-smart-table
=> 826 fix bntable function that disables the action button

projects/ion/src/lib/sidebar/sidebar.component.ts, projects/ion/src/lib/sidebar/sidebar.spec.ts
Resolve https://github.com/Brisanet/ion/pull/809
=> fix: outside click at sidebar component

projects/ion/src/lib/smart-table/smart-table.component.spec.ts, projects/ion/src/lib/smart-table/smart-table.component.ts, projects/ion/src/lib/use-table/use-table.component.ts
reported by @larissa-kamily-brisa
=> fix: order table asc/desc :ambulance:

projects/ion/src/lib/table/table.component.html
=> fix: action disabled on table

stories/Button.stories.mdx
=> docs: button with dropdown documentation

projects/ion/src/lib/core/types/input.ts, projects/ion/src/lib/input/input.component.spec.ts, stories/Input.stories.ts
=> feat: add number type to input

projects/ion/src/lib/core/types/input.ts, projects/ion/src/lib/input/input.component.spec.ts, stories/Input.stories.ts
=> feat: add email type to input :sparkles: #869

projects/ion/src/lib/icon/icon.component.html, projects/ion/src/lib/icon/icon.component.ts
=> fix: click on icon path

projects/ion/src/lib/modal/modal.service.spec.ts, projects/ion/src/lib/modal/modal.service.ts, stories/Modal.stories.mdx
fix #886 
Implementation of a reconfig method da resets the modal configuration.
yarn test modal
=> feat: modal reconfig and test cases added

projects/ion/package.json
Changes the version value to 0.0.77 for package creation.
=> Update package.json to version 0.0.77

projects/ion/src/lib/input-select/input-select.component.scss, projects/ion/src/lib/input/input.component.html, projects/ion/src/lib/input/input.component.scss
fix #888 
Styles and structure changes to fix this behavior
=> fix: input padding

projects/ion/src/lib/select/select.component.scss
=> style: fix bg color on input select :art:

projects/ion/src/lib/core/types/select.ts, projects/ion/src/lib/dropdown/dropdown.component.html, projects/ion/src/lib/dropdown/dropdown.component.spec.ts, projects/ion/src/lib/dropdown/dropdown.component.ts, projects/ion/src/lib/select/select.component.html, projects/ion/src/lib/select/select.component.spec.ts, projects/ion/src/lib/select/select.component.ts, stories/Select.stories.ts
=> 904 add custom proplabel to select and dropdown

projects/ion/src/lib/icon/icon.component.ts
ion-icon was not updating when something changed, like its type on hover.
- Changed the lifecicle that sets the icon's svg inner html to onChanges;
=> fix: icon not updating on change

projects/ion/src/lib/button/button.component.scss
fix #914  
- css changes;
check the button stories
[Button stories](https://62eab350a45bdb0a5818520e-dszzbtskos.chromatic.com/?path=/story/ion-navigation-button--type-primary)
=> fix: button disabled and loading states

projects/ion/src/lib/core/types/dropdown.ts, projects/ion/src/lib/core/types/select.ts, projects/ion/src/lib/dropdown/dropdown.component.html, projects/ion/src/lib/dropdown/dropdown.component.scss, projects/ion/src/lib/dropdown/dropdown.component.spec.ts, projects/ion/src/lib/dropdown/dropdown.component.ts, projects/ion/src/lib/select/select.component.html, projects/ion/src/lib/select/select.component.ts, projects/ion/src/lib/select/select.module.ts, projects/ion/src/lib/shared.module.ts, projects/ion/src/lib/spinner/spinner.module.ts, stories/Dropdown.stories.ts
Implementation of a loading on the dropdown component and making it able to react to changes on the options property.
=> feat: loading on ion-select and ion-dropdown

projects/ion/package.json
=> chore: update version

projects/ion/src/lib/chip/chip.component.html, projects/ion/src/lib/chip/chip.component.spec.ts
=> fix: not showing badge in single choice dropdown

projects/ion/src/lib/modal/component/modal.component.html, projects/ion/src/lib/modal/component/modal.component.spec.ts, projects/ion/src/lib/modal/models/modal.interface.ts, stories/Modal.stories.mdx
fix #941 
Added config option to hide the close button.
- added a ngif to the close button with the config property.
yarn test modal
[Storybook](https://62eab350a45bdb0a5818520e-cwerpfeknf.chromatic.com/)
=> feat: hide close button

projects/ion/src/lib/smart-table/smart-table.component.html, projects/ion/src/lib/table/utilsTable.ts, stories/SmartTable.stories.ts
fix #955 
Changed the conditions to compress the cell data and to show the tooltip based on the new config added.
[Storybook](https://62eab350a45bdb0a5818520e-ryodpgiyda.chromatic.com/?path=/story/ion-data-display-smarttable--with-ellipsis-in-specific-columns)
=> feat: hideLongData on table columns

projects/ion/src/lib/notification/service/notification.container.scss
=> fix: top container margin from notification :art:

projects/ion/src/lib/core/types/index.ts, projects/ion/src/lib/core/types/link.ts, projects/ion/src/lib/ion.module.ts, projects/ion/src/lib/link/link.component.html, projects/ion/src/lib/link/link.component.scss, projects/ion/src/lib/link/link.component.spec.ts, projects/ion/src/lib/link/link.component.ts, projects/ion/src/lib/link/link.module.ts, projects/ion/src/lib/shared.module.ts, projects/ion/src/lib/table/utilsTable.ts, projects/ion/src/public-api.ts, stories/Link.stories.ts
fix #957 
Creation of the link component
yarn test link
=> 957 feat create link component

projects/ion/src/lib/link/link.component.html, projects/ion/src/lib/link/link.component.scss
=> fix: link style tag and width property

.github/workflows/main.yml, .github/workflows/prod.yml, .github/workflows/release.yml
=> 972 remove yarn cache

projects/ion/src/lib/card/card.component.html, projects/ion/src/lib/indicator/indicator.component.html
#963
fix #issue_number
#963
I believe I changed the icon where it says information to the icon
modified file card.component.html and line 13
- Open the pull request that you wish to verify the Storybook Chromatic on.
- At the bottom of the "Checks" comment, click on "Details" next to the "Chromatic/chromatic-deployment" status.
- On the "Checks" page, you will see a list of checks. Select the "Publish to Chromatic" section.
- Scroll down until you find the section "View your Storybook at https://examplelink", that represents the desired link.
</details>
- [✓ ] I have verified that this change complies with our code and contribution policies.
- [✓ ] I have verified that this change does not cause regressions and does not affect other parts of the code.
Remember that the goal of this …
=> change icon indicator name #963

projects/ion/src/lib/simple-menu/simple-menu.component.html
=> style: change simple menu button :art:

projects/ion/src/lib/button/button.component.html, projects/ion/src/lib/button/button.component.spec.ts, projects/ion/src/lib/button/button.component.ts, projects/ion/src/lib/core/types/button.ts, stories/Button.stories.mdx
=> feat: add input text on button with dropdown :sparkles: #995

projects/ion/src/lib/button/button.component.html, projects/ion/src/lib/button/button.component.spec.ts
=> 992 fix style circular button when has dropdown

projects/ion/src/lib/smart-table/smart-table.component.html, projects/ion/src/lib/smart-table/smart-table.component.spec.ts, projects/ion/src/lib/table/table.component.html, projects/ion/src/lib/table/table.component.spec.ts, projects/ion/src/lib/table/utilsTable.ts, projects/ion/src/lib/utils/datePicker.spec.ts, stories/Table.stories.ts
#700
Add new variant to action in table with text in button
=> feat:  new variant to action in table with text in button #700

projects/ion/src/lib/icon/svgs/icons.ts
=> fix: book-open icon being rendered

projects/ion/src/lib/core/types/popover.ts, projects/ion/src/lib/popover/component/popover.component.scss, projects/ion/src/lib/popover/utilsPopover.ts, projects/ion/src/lib/smart-table/mocks/tableActionPopover.ts, projects/ion/src/lib/smart-table/smart-table.component.html, projects/ion/src/lib/smart-table/smart-table.component.spec.ts, projects/ion/src/lib/smart-table/smart-table.module.ts, projects/ion/src/lib/table/table.component.html, projects/ion/src/lib/table/table.component.spec.ts, projects/ion/src/lib/table/table.module.ts, projects/ion/src/lib/table/utilsTable.ts, projects/ion/src/lib/utils/baseTable.ts, stories/SmartTable.stories.ts, stories/smart-tableActionPopover.stories.ts
#1032
[Gravação de tela de 2024-02-28 14-34-16.webm](https://github.com/Brisanet/ion/assets/138057813/4accfa24-7fed-47f6-a62c-1028bf62a658)
=> feat: add popover in action table #1032

projects/ion/src/lib/select/select.component.spec.ts, projects/ion/src/lib/select/select.component.ts
=> feat: close dropdown on select

projects/ion/src/lib/core/types/sidebar.ts, projects/ion/src/lib/sidebar/mocks/sidebarWithFooter.component.ts, projects/ion/src/lib/sidebar/sidebar-group/sidebar-group.component.html, projects/ion/src/lib/sidebar/sidebar-group/sidebar-group.component.scss, projects/ion/src/lib/sidebar/sidebar-group/sidebar-group.component.spec.ts, projects/ion/src/lib/sidebar/sidebar-group/sidebar-group.component.ts, projects/ion/src/lib/sidebar/sidebar-item/sidebar-item.component.html, projects/ion/src/lib/sidebar/sidebar-item/sidebar-item.component.scss, projects/ion/src/lib/sidebar/sidebar-item/sidebar-item.component.spec.ts, projects/ion/src/lib/sidebar/sidebar-item/sidebar-item.component.ts, projects/ion/src/lib/sidebar/sidebar.component.html, projects/ion/src/lib/sidebar/sidebar.component.scss, projects/ion/src/lib/sidebar/sidebar.component.ts, projects/ion/src/lib/sidebar/sidebar.module.ts, projects/ion/src/lib/sidebar/sidebar.spec.ts, projects/ion/src/lib/tooltip/tooltip.component.scss, stories/Sidebar.stories.ts, stories/SidebarWithFooter.stories.ts
fix #1050 
Shrink mode added to the sidebar, scroll capability and a footer insertion possibility.
[Storybook](https://62eab350a45bdb0a5818520e-afdwudjhfq.chromatic.com/?path=/story/ion-navigation-sidebar--with-footer)
=> feat: sidebar shrink mode

projects/ion/src/lib/accordion/accordion-item/accordion-item.component.scss, projects/ion/src/lib/button/button.component.scss, projects/ion/src/lib/checkbox/checkbox.component.scss, projects/ion/src/lib/chip/chip.component.scss, projects/ion/src/lib/radio/radio.component.scss, projects/ion/src/lib/switch/switch.component.scss, projects/ion/src/lib/tab/tab.component.scss, projects/ion/src/styles/shadows/index.scss
fix #1063 
[Storybook](https://62eab350a45bdb0a5818520e-zhxqwehqlk.chromatic.com/)
=> fix: focus state styling

projects/ion/src/lib/core/types/sidebar.ts, projects/ion/src/lib/sidebar/sidebar.component.html, projects/ion/src/lib/sidebar/sidebar.component.scss, projects/ion/src/lib/sidebar/sidebar.component.ts, projects/ion/src/lib/sidebar/sidebar.spec.ts
=> feat: sidebar keep shrunken

projects/ion/src/lib/input-select/input-select.component.html, projects/ion/src/lib/input-select/input-select.component.scss, stories/InputSelect.stories.ts
fix #1077 
The disabled state when a multiple option is selected was not styled.
Include screenshots or GIFs that illustrate the proposed changes. This can be especially useful for user interface changes.
=> fix: input select multiple disabled state

projects/ion/src/lib/core/types/select.ts, projects/ion/src/lib/select/select-item/select-item.component.html, projects/ion/src/lib/select/select-item/select-item.component.scss, projects/ion/src/lib/select/select-item/select-item.component.spec.ts, projects/ion/src/lib/select/select-item/select-item.component.ts, projects/ion/src/lib/select/select.component.html, projects/ion/src/lib/select/select.component.scss, stories/Select.stories.ts
fix #1073 
It was implemented the disabled state on select items and some minor layout adjustments were made.
=> fix: select-item on a disabled ion-select

projects/ion/src/lib/core/types/popover.ts, projects/ion/src/lib/popover/popover.directive.spec.ts, projects/ion/src/lib/popover/popover.directive.ts
fix #1074 
It was added a Subject to be passed as an input to the component so it can informe when to close it.
=> feat: close popover subject

projects/ion/src/lib/core/types/dropdown.ts, projects/ion/src/lib/dropdown/dropdown.component.html, projects/ion/src/lib/dropdown/dropdown.component.spec.ts, projects/ion/src/lib/dropdown/dropdown.component.ts, stories/Button.stories.mdx, stories/Dropdown.stories.ts
fix #1062
When the dropdown is required and the option is being hovered, the icon is not changed:
[Gravação de tela de 2024-04-12 09-42-26.webm](https://github.com/Brisanet/ion/assets/138057813/7b68ffaf-e855-43f4-b5af-44e3b930de89)
when the dropdown is required and multiple:
[Gravação de tela de 2024-04-12 09-49-17.webm](https://github.com/Brisanet/ion/assets/138057813/b8a4897d-038a-4d16-8860-1f63936e4340)
=> fix: dropdown icon behavior in required mode #1062

projects/ion/src/lib/link/link.component.scss, projects/ion/src/lib/smart-table/smart-table.component.html, projects/ion/src/lib/smart-table/smart-table.component.spec.ts, projects/ion/src/lib/table/utilsTable.ts, projects/ion/src/lib/utils/types.ts, stories/SmartTable.stories.ts
fix #1093 
Added a option to the user provide a tooltip config for the link.
=> 1093 feat add tooltip in link row in smart table

projects/ion/src/lib/core/types/steps.ts, projects/ion/src/lib/step/step.component.html, projects/ion/src/lib/step/step.component.spec.ts, projects/ion/src/lib/step/step.component.ts, stories/Step.stories.ts
fix #1096 
- Disable individual step item.
- Reload steps after change
=> feat: disable individual step item

projects/ion/src/lib/input-select/input-select.component.ts, stories/InputSelect.stories.ts
Fix docs visualization on input select.
=> docs: fix input select docs

projects/ion/src/lib/input-select/input-select.component.html, projects/ion/src/lib/input-select/input-select.component.scss, projects/ion/src/lib/input-select/input-select.component.ts, projects/ion/src/lib/input-select/input-select.module.ts
##1105
This PR have the purpose to implement the validation states on input selection component.
=> feat: input select validation property

projects/ion/src/lib/checkbox/checkbox.component.html, projects/ion/src/lib/checkbox/checkbox.component.scss
Fixes some styles in the checkbox component that were different from the prototype.
=> fix: styles on checkbox component

projects/ion/src/lib/tooltip/tooltip.component.html, projects/ion/src/lib/tooltip/tooltip.component.spec.ts, projects/ion/src/lib/tooltip/tooltip.component.ts, projects/ion/src/lib/tooltip/tooltip.directive.spec.ts, projects/ion/src/lib/tooltip/tooltip.directive.ts
=> feat: add custom class on tooltip

projects/ion/src/lib/modal/component/modal.component.scss, projects/ion/src/lib/modal/component/modal.component.spec.ts, projects/ion/src/lib/modal/component/modal.component.ts
#1130 
Sadly I had to use setTimeout to be able to set the focus to the dialog, any other solution that I tried didn't work.
I also did test this on Yoda and this solution it's working as expected:
[Screencast from 2024-09-05 11-52-43.webm](https://github.com/user-attachments/assets/96a48aa8-b2f6-47a6-b5af-1fb195d9830c)
=> fix: remove inert attr use and fix focus issues

projects/ion/src/lib/input-select/input-select.component.html, projects/ion/src/lib/input-select/input-select.component.ts
=> fix: click outside on input select dropdown

projects/ion/src/lib/button/_button.theme.scss, projects/ion/src/lib/triple-toggle/_triple-toggle.theme.scss, projects/ion/src/lib/triple-toggle/triple-toggle.component.scss
fix #1181 
[Gravação de tela de 2024-11-11 11-28-23.webm](https://github.com/user-attachments/assets/79a06eda-294a-4290-a9cc-7ce62df1f59b)
=> style: adding dark theme styles in triple toggle

projects/ion/src/lib/indicator/_indicator.theme.scss
style #1191 
[Gravação de tela de 2024-11-14 10-47-02.webm](https://github.com/user-attachments/assets/8c9d13fc-ae76-443e-b63a-bcdca891d2fa)
=> style: adding dark theme styles in indicators

projects/ion/src/lib/popover/component/_popover.theme.scss
=> style: adding dark theme styles in popover

projects/ion/src/lib/dropdown/_dropdown.theme.scss, projects/ion/src/lib/dropdown/dropdown.component.scss, projects/ion/src/lib/select/_select.theme.scss, projects/ion/src/lib/select/select-item/select-item.component.scss, projects/ion/src/lib/select/select.component.html, projects/ion/src/lib/select/select.component.scss
style #1201 
[Gravação de tela de 2024-11-25 16-42-35.webm](https://github.com/user-attachments/assets/2213ce37-3855-4c76-9a0f-3ceacfbf5851)
=> style: adding dark theme styles in select

projects/ion/src/lib/input/_input.theme.scss
Associate the issue number with the title of the pull request. If you don't have an associated issue, you should create one. Including an issue number helps provide context and traceability to the proposed changes in the pull request.
style #1200 
[Gravação de tela de 2024-11-26 10-11-56.webm](https://github.com/user-attachments/assets/d676f99c-a38f-4a91-a565-3572a416f436)
=> style: adding dark theme styles in input

projects/ion/src/lib/input-select/_input-select.theme.scss, projects/ion/src/lib/input-select/input-select.component.html, projects/ion/src/lib/input-select/input-select.component.scss
=> style: adding dark theme styles in input select

projects/ion/package.json
=> chore: updating ion version

projects/ion/src/lib/alert/_alert.theme.scss, projects/ion/src/lib/alert/alert.component.scss, projects/ion/src/lib/popconfirm/_popconfirm.theme.scss, projects/ion/src/lib/popconfirm/popconfirm.component.scss, projects/ion/src/lib/popover/component/_popover.theme.scss, projects/ion/src/lib/popover/component/popover.component.scss
fix #1209 
[Gravação de tela de 2024-11-29 13-06-47.webm](https://github.com/user-attachments/assets/b6188e80-0e8f-4d82-9d28-2493cb821a48)
=> style: [1209] add dark theme styles in popconfirm

projects/ion/src/lib/input-area/_input-area.theme.scss, projects/ion/src/lib/input-area/input-area.component.html, projects/ion/src/lib/input-area/input-area.component.scss
style #1212 
[Gravação de tela de 2024-11-29 15-59-43.webm](https://github.com/user-attachments/assets/dcee7dc8-3a59-4f5f-b79a-0f6d7dac39e9)
=> style: adding dark theme styles in input area

projects/ion/src/lib/step/_step.theme.scss, projects/ion/src/lib/step/step.component.scss
style #1213 
[Gravação de tela de 2024-12-02 16-41-01.webm](https://github.com/user-attachments/assets/d6599b33-f8e4-4112-b535-9edb86ce33a4)
=> style: adding dark theme styles in step

projects/ion/src/lib/checkbox/_checkbox.theme.scss
fix #1214 
[Gravação de tela de 2024-12-02 17-00-12.webm](https://github.com/user-attachments/assets/a2419a03-946a-4d82-87b8-ea308f8dcb7d)
=> style: adding dark theme styles in checkbox

projects/ion/src/lib/link/_link.theme.scss, projects/ion/src/lib/notification/component/_notification.theme.scss, projects/ion/src/lib/notification/component/notification.component.scss
style #1216 
[Gravação de tela de 2024-12-02 17-04-30.webm](https://github.com/user-attachments/assets/d3090e49-1421-476f-b8a8-590c60dd7d26)
=> style: adding dark theme styles in link

projects/ion/package.json
=> chore: updating ion version to 106

projects/ion/src/lib/switch/_switch.theme.scss
style #1224 
[Gravação de tela de 2025-01-08 10-46-35.webm](https://github.com/user-attachments/assets/96891a5c-b3bc-4cc8-9fc2-469c82d3047e)
=> style: adding dark theme in switch

projects/ion/src/lib/sidebar/_sidebar.theme.scss, projects/ion/src/lib/sidebar/sidebar.component.scss, projects/ion/src/lib/triple-toggle/_triple-toggle.theme.scss, projects/ion/src/lib/triple-toggle/triple-toggle.component.scss
style #1226 
[Gravação de tela de 2025-01-09 10-36-50.webm](https://github.com/user-attachments/assets/779c16a8-2b01-407a-87ef-3fb388ec1d9d)
=> style: adjusting dark theme in sidebar and triple toggle

projects/ion/src/lib/smart-table/smart-table.component.html, projects/ion/src/lib/table/utilsTable.ts, stories/smart-tableActionPopover.stories.ts
=> fix: add ionPopoverStopCloseOnScroll in smartable

projects/ion/src/lib/tab/_tab.theme.scss, projects/ion/src/lib/tab/tab.component.scss
style #1228
[Gravação de tela de 2025-01-10 10-58-51.webm](https://github.com/user-attachments/assets/9cb21a17-b98a-4cf5-80c7-b9d2aa706ce1)
=> 1228 style add dark theme style in tab

projects/ion/src/lib/dropdown/dropdown.component.scss
=> style: correcting border colors in dropdown

projects/ion/package.json
=> chore: updating ion version to 109

projects/ion/package.json
Update ion version to v0.0.113
=> chore: update version to v0.0.113
