Brisanet/ion

- projects/ion/src/lib/indicator/indicator.component.html
Indicator now considers the space of the footer, even if there is no action.
> fix: fix indicator alignment

- projects/ion/src/lib/smart-table/smart-table.component.html
- projects/ion/src/lib/smart-table/smart-table.component.spec.ts
- projects/ion/src/lib/smart-table/smart-table.component.ts
- stories/SmartTable.stories.ts
- Add a debounce time that can be given on smart table config, that will only emit one sort event after a given time, independent of how many times the user clicked on sort button;
- Fix console errors when smart table tests were run.
> feat: debounce time to order button

- projects/ion/src/lib/core/types/smart-table.ts
- projects/ion/src/lib/smart-table/smart-table.component.spec.ts
- projects/ion/src/lib/smart-table/smart-table.component.ts
- projects/ion/src/lib/table/utilsTable.ts
Move interfaces from `smart-table.component.ts` to `cores/types/smart-table.ts`.
> 🚚 fix: smart-table interfaces exports

- stories/Tooltip.stories.ts
fix wrong import in tooltipe story
- stories/Tooltip.stories.ts
before: 
after:
> 498 hotfix fix tooltip imports

- projects/ion/src/lib/table/table.component.scss
When I add an action, and some other column has a defined width, the columns that have the width are all at the minimum size, and the action column occupies all the remaining space.
That the ConfigSmartTable can accept a width for the action column.
1. Create a smarttable with columns with a width: 1
2. Add an action with the definition of an icon and a label
```ts
public clientTableConfig: ConfigSmartTable<any> = {
pagination: { total: 1, offset: 0, itemsPerPage: 10, page: 1 },
data: [],
columns: [{ key: 'cliente_id', label: 'Código do cliente', width: 1 }],
actions: [
{
icon: 'trash',
label: 'apagar',
call(row) {
console.log({ row });
},
},
],
};
```
> fix: smarttable with columns misaligned when add actions

- projects/ion/src/lib/tooltip/tooltip.component.html
- projects/ion/src/lib/tooltip/tooltip.component.scss
- projects/ion/src/lib/tooltip/tooltip.component.ts
- projects/ion/src/lib/tooltip/tooltip.directive.spec.ts
- projects/ion/src/lib/tooltip/tooltip.directive.ts
- stories/Tooltip.stories.ts
Tooltip now receives a TemplateRef, that allow users to insert any type of HTML to be displayed on tooltip. 
It can be used with TooltipTitle to create a "subtitle":
> ✨ feat: template ref on tooltip

- projects/ion/src/lib/table/table.component.scss
#510 
Actions column header of smart-table have style issues
- set a safe `z-index` on elements inside the table header
- set the same style to `th` tags
> style: fix actions colmun header

- projects/ion/src/lib/sidebar/sidebar-group/sidebar-group.component.html
- projects/ion/src/lib/sidebar/sidebar-group/sidebar-group.component.scss
- projects/ion/src/lib/sidebar/sidebar-group/sidebar-group.component.spec.ts
- projects/ion/src/lib/sidebar/sidebar-group/sidebar-group.component.ts
- projects/ion/src/lib/sidebar/sidebar.component.html
- projects/ion/src/lib/sidebar/sidebar.component.ts
- projects/ion/src/lib/sidebar/sidebar.spec.ts
- projects/ion/src/lib/sidebar/utils.spec.ts
- projects/ion/src/lib/sidebar/utils.ts
- stories/Sidebar.stories.ts
When a sidebar group has an action, this action will be called when the title in the header is clicked. The user will be able to toggle the group when clicking on the arrow icon.
[Screencast from 09-03-2023 13:18:51.webm](https://user-images.githubusercontent.com/57760325/224086328-f97eb77f-03eb-4368-b0be-7fc2680c6692.webm)
---
When a sidebar group doesn't have an action, the user will be able to toggle the group clicking on header, not just on the arrow icon.
[Screencast from 09-03-2023 13:19:21.webm](https://user-images.githubusercontent.com/57760325/224086494-ec0eb0de-130d-4736-81d2-c7b6316def3c.webm)
(Both examples are available on Storybook)
> feat: sidebar group can call an action when clicking on its title

- projects/ion/src/lib/chip/chip.component.html
- projects/ion/src/lib/chip/chip.component.spec.ts
- projects/ion/src/lib/chip/chip.component.ts
Validation was added to ngOnChanges for the chip to change the label when the dropdown options are changed via TS
> fix: adding validation of changes to the label

- projects/ion/src/lib/dropdown/dropdown.component.spec.ts
- projects/ion/src/lib/dropdown/dropdown.component.ts
showing clear button when there are selected values by default
set clear button visibility on init
The storybook had some rendering bugs that make visual tests a bit difficult, so to test I created a stories.ts (that has not been committed) with a mock @component to render the dropdown inside it and work around these storybook bugs
results in dropdown rendered inside mock test component:
> fix: showing clear button when there are selected values by default

- projects/ion/package.json
- projects/ion/src/lib/dropdown/dropdown.component.scss
- projects/ion/src/lib/message/message.component.scss
- projects/ion/src/lib/modal/component/modal.component.scss
- projects/ion/src/lib/notification/notification.component.scss
- projects/ion/src/lib/popconfirm/popconfirm.component.scss
- projects/ion/src/lib/popover/component/popover.component.scss
- projects/ion/src/lib/tooltip/tooltip.component.scss
- projects/ion/src/styles/index.scss
- projects/ion/src/styles/z-indexes/index.scss
Apply z-index pattern to elements that float on the screen, overlapping other components.
Avoid randomly choosing z-indez for components, which could lead to some strange behavior, such as a dropdown appearing below other elements on the screen, when it should actually appear above them.
Below is an image with expected z-index values for the listed elements, categorized by levels:
List of elements and their current z-index:
- Modal: 99
- Message: (Não há)
- Dropdown: (Não há)
- Notification: (Não há)
- Popconfirm: 1.000 (O valor máximo é 999)
- Popover: 1.000 (O valor máximo é 999)
- Tooltip: 100
> feat: apply z-index pattern at overly elements

- projects/ion/src/lib/button/button.component.scss
- projects/ion/src/lib/pagination/pagination.component.ts
- projects/ion/src/lib/smart-table/smart-table.component.ts
- projects/ion/src/lib/table/table.component.scss
When using pagination component in a project, through the SmatTable component, some behaviors  that need to be resolved were noticed:
- When selecting a number of items per page, the option selector appears broken in the layout;
- Also, it has a strange behavior over the table, causing the table footer to jitter slightly when I open the selector.
- That selector for the number of items per page is completely visible;
- That selector is usable, even when placed at the bottom of a page, opening the options upwards.
There are two other notes about pagination involving the table, so I'll leave them on record as another issue to resolve, leaving them here for informational purposes only:
- When pagination receives 0 as the total items value, it disappears;
- When using paging, the table is …
> fix: adjustments to improove and fix some behaviors at pagination

- projects/ion/src/lib/chip/chip.component.scss
when the space available for the chip was reduced, it would break the line, so I implemented the "white-space: nowrap;" styling. to fix that so it keeps the original size
`.container-icon-text {
display: flex;
align-items: center;
white-space: nowrap;
gap: spacing(1);
}`
before: 
after: 
reference: https://developer.mozilla.org/en-US/docs/Web/CSS/white-space
> fix: fixing break a line

- projects/ion/src/lib/popconfirm/popconfirm.component.scss
- stories/Table.stories.ts
fixed #587 css z-index on popconfirm.
> fix: popconfirm on footer table css :ambulance: #587

- projects/ion/src/lib/badge/badge.component.scss
I added a min width to the span so that the size adjusts when there is only one digit.
> fix: size adjustment when there is one digit (#572)

- projects/ion/src/lib/pagination/pagination.component.html
- projects/ion/src/lib/pagination/pagination.component.scss
- projects/ion/src/lib/pagination/pagination.component.spec.ts
- projects/ion/src/lib/pagination/pagination.component.ts
- projects/ion/src/lib/pagination/utils/ellipsis.component.ts
fix #512 
When the number of numeric buttons is greater than or equal to 10, the advanced pattern is displayed and when clicking on the ellipsis, the selection must be returned or advanced to 5 numbers, when it is less than or equal to 9, the simple pattern is displayed.
Simple Pattern 
Advanced Standard 
When hover on the ellipsis 
When the ellipsis is clicked and the next 5 numbers are displayed
> feat: ellipsis in pagination component (#512)

- projects/ion/src/lib/pagination/pagination.component.ts
The ngChanges of the table was emitting an extra event when the total was changed, now a validation has been added to adjust this behavior.
> fix: adding event emission validation for pagination

- projects/ion/src/lib/smart-table/smart-table.component.html
- projects/ion/src/lib/smart-table/smart-table.component.spec.ts
- projects/ion/src/lib/table/table.component.html
- projects/ion/src/lib/table/table.component.spec.ts
- projects/ion/src/lib/table/utilsTable.ts
- stories/SmartTable.stories.ts
- stories/Table.stories.ts
fix #612 
Add danger boolean to actions so it can render button as danger type:
Add dynamic description to popconfirm, so we can access row data and customize description:
Storybook: https://62eab350a45bdb0a5818520e-exucuzowes.chromatic.com/
> feat: add type danger to table action and popconfirm dynamic description

- projects/ion/src/lib/button/button.component.scss
- stories/Button.stories.mdx
fix #623 
The danger class was overwriting the disabled, so I added important to the fill property.
- added a new story to reproduce the error;
- added important to the fill on the ion-icon selector.
Check story "disabled in ghost danger icon button" on the storybook.
[Storybook Link](https://62eab350a45bdb0a5818520e-gcljhmkqet.chromatic.com/?path=/story/ion-navigation-button--disabled-in-ghost-danger-icon-button)
> fix: icon color when a ghost danger button is disabled

- projects/ion/src/lib/chip/chip.component.scss
fix #563 
The colors of the border, text and background in the default and press events of the selected state were wrong, so I changed to the right colors on the selectors in the scss file.
- Changed the colors of the border, background and text in the default and press events.
Check the Navigation > Chips > Selected story of the storybook
[Storybook Link](https://62eab350a45bdb0a5818520e-gwrvnbntjt.chromatic.com/?path=/story/ion-navigation-chips--selected)
> fix: border, background and text colors adjusted on the chip(selected state) component

- projects/ion/src/lib/pagination/pagination.component.html
- projects/ion/src/lib/pagination/pagination.component.ts
In the pagination component, while it is disabled, it is possible to click multiple times and the pagination will advance, even though the button appears disabled.
> fix: disable event emitter when table is loading

- projects/ion/src/lib/pagination/pagination.component.html
- projects/ion/src/lib/pagination/pagination.component.spec.ts
- projects/ion/src/lib/pagination/pagination.component.ts
- projects/ion/src/lib/select/select.component.scss
- projects/ion/src/lib/smart-table/smart-table.component.html
- projects/ion/src/lib/smart-table/smart-table.component.spec.ts
- projects/ion/src/lib/table/table.component.scss
Fixed the issue where when the table was loading it was possible to change the number of pages while it shouldn't be possible.
Feat animation of ion-smart-table when table status is loading
- When the table is loading it will not be possible to change the number of items per page
- Create animated of ion-smart-table pagination when table status is loading
When clicking to page through the ion-smart-table table using a SLOW 3G network, you should not be able to change the number of items per page
https://github.com/Brisanet/ion/assets/54484070/15a35c71-60ea-4ae6-be48-ba2e7ad24427
> 640 fix ion smart table

- projects/ion/src/lib/popconfirm/popconfirm.directive.spec.ts
- projects/ion/src/lib/popconfirm/popconfirm.directive.ts
fix #644 
This PR changes the behavior of popconfirm, because the way it is currently it is possible to open numerous popsconfirms making it a mess, and this switch allows only 1 to be shown at a time.
- It is only possible to open a popconfirm
Before: 
https://github.com/Brisanet/ion/assets/54484070/450f9419-3e77-48a8-8669-23b06ae1fe1e
After:
https://github.com/Brisanet/ion/assets/54484070/22e63478-36c7-4309-84f2-465ee226d330
> fix: fixing issue where popconfirm opened more than one

- projects/ion/src/lib/pagination/pagination.component.html
- projects/ion/src/lib/pagination/pagination.component.spec.ts
- projects/ion/src/lib/pagination/pagination.component.ts
fix #655 
When clicking the button to navigate to the page that correspond to the current page, an event was emmited, so I defined a funcion that had a single responsability of handling the button click, and passed it to the click event on the component, so it could verify if the selcted page is the current and return if true, if not, executes the old function to emmit the event as expected.
- Defined a new function with a Guard Clause to return early if the page selected was the one that was already active, and if not, just calls the selectPage function to do the logic as before;
- Passed this new function to the click replacing the previous one;
- Implemented a new test assertion to verify if no event was being emmited in this scenario.
run "yarn test pagination"
[Storybook …
> fix: dont emit when click the same page button

- projects/ion/src/lib/badge/badge.component.scss
When there is only one number on the badge, its format is not a perfect circle, being slightly flattened. To achieve a better rounded effect, it is necessary that the width is at least equal to the height, which is 16px.
When the badge contains a single digit number, it should be as close to a perfect circle as possible.
> fix: adjust width of badge

- projects/ion/src/lib/tab-group/tab-group.component.html
- projects/ion/src/lib/tab-group/tab-group.component.spec.ts
- stories/TabGroup.stories.ts
fix #682 
The tab component have a disabled input property, but the tabgroup wasn't using it, so I added the property and passed to it the disabled expected value from the received tabs.
- On the html of the tabgroup component, I passed the disabled property to the tab component, with the value from the current tab;
- created a story to verify the changes, passing one tab with the disabled true;
- created a test assertion to verify if, when is passed the disabled to true, the tab component is really disabled.
run yarn test tab-group, or check the story: horizontal disabled from the storybook
[storybook](https://62eab350a45bdb0a5818520e-risyvibyuu.chromatic.com/?path=/story/ion-navigation-tabgroup--horizontal-disabled)
> 682 add disabled state on tabgroup

- projects/ion/src/lib/tag/tag.component.scss
#571 
fixing tag spacing and also line-height
figma: 
before: 
after:
> fix: fixing spaces in tag

- projects/ion/src/lib/core/types/dropdown.ts
- projects/ion/src/lib/core/types/select.ts
- projects/ion/src/lib/dropdown/dropdown.component.spec.ts
- projects/ion/src/lib/dropdown/dropdown.component.ts
- projects/ion/src/lib/select/select.component.html
- projects/ion/src/lib/select/select.component.ts
- stories/Select.stories.ts
fix #683 
The select didnt had a max length option, so to implement it, I added a property to the select component and to the dropdown, so it could be passed from one to another and the dropdown could be able to do the validation and work as expected.
- Defined a Input property on the  components, select and dropdown;
- passed the maxLength to the dropdown on the html of the select;
- defined a guard to return early on the "manageMultipleOptions" method if the maxlength was already reached;
- implemented test assertions on the dropdown, to ensure these behaviors.
Run yarn test dropdown or check the story select with multiple option of the storybook
[Storybook](https://62eab350a45bdb0a5818520e-cpcqmfwlrv.chromatic.com/)
> 683 add max length into select component

- projects/ion/src/lib/chip/chip.component.spec.ts
- projects/ion/src/lib/chip/chip.component.ts
fix #707
If you create a chip with an option already selected, the badge value will be updated.
- Update the badge value on chip creation
> fix: update badge value when chip is create with option selected

- projects/ion/src/lib/core/types/dropdown.ts
- projects/ion/src/lib/dropdown/dropdown.component.html
- projects/ion/src/lib/dropdown/dropdown.component.spec.ts
- projects/ion/src/lib/dropdown/dropdown.component.ts
- projects/ion/src/lib/no-data/no-data.component.spec.ts
- projects/ion/src/lib/no-data/no-data.module.ts
- projects/ion/src/lib/shared.module.ts
- stories/Dropdown.stories.ts
feat #526
noData template for when there are no options in the dropdown
Dropdown noData: 
In the Select: 
In the Chip with search:
> feat: create template no data content in dropdown #526

- projects/ion/src/lib/core/types/smart-table.ts
- projects/ion/src/lib/smart-table/smart-table.component.html
- projects/ion/src/lib/smart-table/smart-table.component.spec.ts
- projects/ion/src/lib/smart-table/smart-table.component.ts
- projects/ion/src/lib/smart-table/smart-table.module.ts
- projects/ion/src/lib/tooltip/tooltip.directive.ts
- stories/SmartTable.stories.ts
fix #702 
Implementation of the tooltip directive in the action buttons of the table. Were created two buttons that are conditionally displayed, if were informed tooltip configs, the button with the tooltip directive is rendered, if not, the regular one. It was also added a ngcontainer to receive a body to be passed to the tooltip. 
- Tooltip directive adjusted to close the tooltip on click if the trigger mode is hover, so when the popconfirm is opened the tooltip doesnt stay behind it;
- Added a button with the tooltip directive on the smart table to be rendered when tooltip configs are informed;
- Tests implemented to verify if the popconfirm was still opening and the tooltip was working as expected.
Run yarn test smart-table and see the story 
[Gravação de tela de 23-06-2023 …
> 702 add tooltip in action button on table

- projects/ion/src/lib/smart-table/smart-table.component.html
- projects/ion/src/lib/table/table.component.html
- projects/ion/src/lib/table/table.component.spec.ts
- projects/ion/src/lib/table/table.component.ts
- projects/ion/src/lib/table/utilsTable.ts
- stories/Table.stories.ts
feat #290 
This PR adds the possibility to customize the table rows of the ion-table and ion-smart-table components
In the Storybook it was not possible to recreate the example, but I left a step by step on how to use it.
https://62eab350a45bdb0a5818520e-xdclkvquht.chromatic.com/?path=/docs/ion-data-display-table--table-custom-row
> 290 create custom row to table

- projects/ion/src/lib/tooltip/tooltip.directive.spec.ts
- projects/ion/src/lib/tooltip/tooltip.directive.ts
#747 
The intention of this feature is to make it so that when an empty string is passed to the ionTooltipTitle, the tooltip will not be rendered
feat: #747 
before:
> feat: not render tooltip when ionTooltipTitle is empty #747 

- projects/ion/src/lib/core/types/select.ts
- projects/ion/src/lib/select/select.component.html
- projects/ion/src/lib/select/select.component.scss
- projects/ion/src/lib/select/select.component.spec.ts
- projects/ion/src/lib/select/select.component.ts
- stories/Select.stories.ts
feat #749 
implemented required validation and issuing the field clear event
https://62eab350a45bdb0a5818520e-zjoxxufkdf.chromatic.com/?path=/story/ion-data-entry-select--required
> Add required param on ion-select and emit event when unselect a option

- projects/ion/src/lib/pagination/pagination.component.spec.ts
- projects/ion/src/lib/pagination/pagination.component.ts
fix #753 
This adds a validation on the remount method to check if the current page is still part of the pagination to call the function with the page number page as usual and if it isn't, the remount calls the selectPage with the last  page.
It was also added a test previously to ensure this behavior.
run yarn test pagination
[Gravação de tela de 17-07-2023 16:29:42.webm](https://github.com/Brisanet/ion/assets/98463818/e7ed6405-cf7a-4867-aa3e-3c30e97bfed6)
[Storybook](https://62eab350a45bdb0a5818520e-duoqhyotvk.chromatic.com/)
> fix: pagination selection when changing qtdPerPage

- projects/ion/src/lib/core/types/smart-table.ts
- projects/ion/src/lib/smart-table/smart-table.component.html
- projects/ion/src/lib/smart-table/smart-table.component.spec.ts
- projects/ion/src/lib/smart-table/smart-table.component.ts
- projects/ion/src/lib/table/table.component.scss
- stories/SmartTable.stories.ts
fix #767 
Added a config property on the smart table to allow the user to compress cell data and show a tooltip with is full content.
- Definition of a class that does the compressing and adds the ellipsis;
- definition of a property that holds the condition to add the previous defined class to the cell;
- addition of the tooltip to the table's cells that will only appear if the new property is true and the container has overflown content.
- implementation of tests in a new describe;
Run yarn test smart-table or check the specifc story: Smart Table > With Ellipsis On Cell
[Storybook](https://62eab350a45bdb0a5818520e-ffypptiqzo.chromatic.com/)
> 758 feat ellipsis on table cell

- projects/ion/src/lib/smart-table/smart-table.component.html
- projects/ion/src/lib/smart-table/smart-table.component.spec.ts
- projects/ion/src/lib/smart-table/smart-table.component.ts
- projects/ion/src/lib/table/table.component.html
- projects/ion/src/lib/table/table.component.spec.ts
- projects/ion/src/lib/table/table.component.ts
- projects/ion/src/lib/table/table.module.ts
- projects/ion/src/lib/table/utilsTable.ts
- stories/SmartTable.stories.ts
- stories/Table.stories.ts
feat #737
Added tooltip setting for table column
[Gravação de tela de 2023-07-27 10-42-56.webm](https://github.com/Brisanet/ion/assets/93842972/67c29f02-9052-4425-8755-c8a4db451a42)
> feat: add tooltip to column name on ion table #737

- projects/ion/src/lib/popconfirm/popconfirm.component.html
- projects/ion/src/lib/popconfirm/popconfirm.directive.spec.ts
fix #786 
Change of the button click event listener to ionOnClick and test adjusments.
> fix: ion button click event on popconfirm and test adjusments

- projects/ion/src/lib/radio/radio.component.html
fix #782 
This fixes the issue that was occurring when a function was passed to the ion-radio element and the user clicked on the radio label, the function was being called twice. Analyzing the error it was seen that the implementation of the "for" in the label was causing a problem known as "Event bubbling" in which the label was propagating the click to the input and executing it twice, causing duplicity.
- Remove the "for" attribute from the label and pass the click function to it, to maintain the functionality
> refactor: fixing ion-radio click on label #782

- projects/ion/src/lib/no-data/no-data.component.scss
The no data component label was receiving a margin bottom by default when added to projects. It was needed to reset it in the component itself
> fix: no data label margin reset

- projects/ion/src/lib/chip-group/chip-group.component.spec.ts
- projects/ion/src/lib/chip/chip.component.spec.ts
- projects/ion/src/lib/chip/chip.component.ts
- stories/Chip.stories.ts
fix #853 
- Added a call of setBadgeValue to update the badge when we have the value.
yarn test chip
> fix: chip badge not geting the initial selecteds

- projects/ion/src/lib/indicator/indicator.component.html
fix #850 
To achieve the validation necessary without changing the whole indicator types structure, only changes in the html were made.
- changed the logic in the indicator footer buttons;
- now it will render the open popover button only if the popover config is informed, not necessarily only depending of the button type.
> fix: indicator footer buttons render conditions

- projects/ion/src/lib/core/types/input.ts
- projects/ion/src/lib/icon/mock/list-icons.module.ts
- projects/ion/src/lib/input/input.component.html
- projects/ion/src/lib/input/input.component.scss
- projects/ion/src/lib/input/input.component.spec.ts
- projects/ion/src/lib/input/input.component.ts
- projects/ion/src/lib/picker/date-picker/date-picker-input/date-picker-input.component.html
- projects/ion/src/lib/picker/date-picker/date-picker-input/date-picker-input.component.spec.ts
- projects/ion/src/lib/picker/date-picker/date-picker-input/date-picker-input.component.ts
- stories/Input.stories.ts
fix #872 
Change of the button elements inside the ion input for a single ion button, that can adapt to a icon button or a regular button.
- The two buttons elements were removed ;
- one ionInputProperty removed, leaving just the inputButton;
- added the inputButtonConfig property;
- the ng classes were removed from the input and one was set to the input container;
- added a ionButton with its main properties;
- changed the styles to adapt the ion button to this scenario;
- addapted the tests to the new input button specification;
- changes on the date-picker to adapt to the new inputButton;
yarn test input
[Storybook](https://62eab350a45bdb0a5818520e-xevttaolfl.chromatic.com/?path=/story/ion-data-entry-input--input-button)
> fix: ion input button

- projects/ion/src/lib/input-select/input-select.component.html
- projects/ion/src/lib/input-select/input-select.component.spec.ts
- projects/ion/src/lib/input-select/input-select.component.ts
fix #889 
Added a value emittion both on the input blur event and on the option change.
yarn test input-select
> fix: values emittion when changing option

- projects/ion/src/lib/smart-table/smart-table.component.html
- projects/ion/src/lib/smart-table/smart-table.component.spec.ts
- projects/ion/src/lib/table/utilsTable.ts
- projects/ion/src/lib/tag/tag.component.scss
- stories/SmartTable.stories.ts
- yarn.lock
Insert tooltipKey in tag cell on smart-table
feat #897 
- insert tooltip key 
In columns of smart-table:
> 897 feat insert tooltip in tag cell on smart table

- projects/ion/src/lib/tooltip/tooltip.component.scss
fix #928 
Change on the tooltip index so it wont be behind elements with high zindexes
- Chaged its zindex from low to mid.
> fix: tooltip zindex

- projects/ion/src/lib/chip-group/chip-group.component.html
- projects/ion/src/lib/chip-group/chip-group.component.spec.ts
- projects/ion/src/lib/chip-group/chip-group.component.ts
- projects/ion/src/lib/chip/chip.component.spec.ts
- projects/ion/src/lib/chip/chip.component.ts
- projects/ion/src/lib/core/types/chip.ts
fix #926 
Adding functionality so that when a chip has a dropdown and it is closed, the chip now loses its selected style. Fixed both on the chip and on the chip group
- In the event of closing the dropdown, the process to remove the style (chip.component)
- Chip now emits, in its events, when the dropdown is closed. Change necessary to fix the problem in the chip-group3
- Chip-group now have the function to clear the chip selecteds when the dropdown-close event is emmited
Open the chip dropdown and then click outside the component
> refactor: fixing style error occurring in certain chip flows #926

- projects/ion/src/lib/core/types/dropdown.ts
- projects/ion/src/lib/dropdown/dropdown.component.html
- projects/ion/src/lib/dropdown/dropdown.component.scss
- projects/ion/src/lib/dropdown/dropdown.component.spec.ts
- stories/Dropdown.stories.ts
fix #945 
Now is possible add a icon in option
look here! https://62eab350a45bdb0a5818520e-tkucgwrtdo.chromatic.com/?path=/story/ion-navigation-dropdown--option-with-icon
> feat: add icon to dropdown option #945 :sparkles:

- projects/ion/src/lib/table/table.component.scss
fix #953 
Removed the word break css property so it could behave as expected.
> fix: table cell word break

- projects/ion/src/lib/table/table.component.scss
fix #960 
- Added a border radius to thead's first and last th child elements.
> fix: table border radius

- projects/ion/src/lib/tooltip/tooltip.directive.spec.ts
- projects/ion/src/lib/tooltip/tooltip.directive.ts
- stories/Tooltip.stories.ts
#876
now when there is a dropdown open on the host element, the tooltip will not be rendered
[Gravação de tela de 2023-11-22 15-19-31.webm](https://github.com/Brisanet/ion/assets/138057813/2042978a-ab4b-4050-a60e-4629d931b721)
> fix: tooltip should not be visible when hovering a dropdown inside a button #876

- projects/ion/src/lib/sidebar/sidebar.component.html
- projects/ion/src/lib/sidebar/sidebar.component.ts
- projects/ion/src/lib/sidebar/sidebar.spec.ts
fix #970 
Now the sidebar has the expected behavior. When clicked on the logo and the closeOnSelect property is true. The sidebar calls the logoAction and closes the sidebar.
[Gravação de tela de 2023-12-01 11-36-14.webm](https://github.com/Brisanet/ion/assets/138057627/404f5843-dc56-4713-8789-6211284f60da)
> fix: siber closing when clicked in logo

- projects/ion/src/lib/core/types/indicator.ts
- projects/ion/src/lib/indicator/indicator.component.html
- projects/ion/src/lib/indicator/indicator.component.spec.ts
- projects/ion/src/lib/indicator/indicator.component.ts
- stories/Indicator.stories.ts
#987 
Pass text to create a tooltip on the second value of the indicator.
> feat: add second tooltip in indicator

- projects/ion/src/lib/chip-group/chip-group.component.spec.ts
- projects/ion/src/lib/chip-group/chip-group.component.ts
fix #998 
Since the chip-group has a internal logic to select the chip, was necessary to return early in the disabled cases.
yarn test chip-group
[Story](https://62eab350a45bdb0a5818520e-bkjelofgvi.chromatic.com/?path=/story/ion-navigation-chipgroup--disable-default)
> fix: return when disabled

- projects/ion/src/lib/core/types/indicator.ts
- projects/ion/src/lib/indicator/indicator.component.html
- projects/ion/src/lib/indicator/indicator.component.scss
- projects/ion/src/lib/indicator/indicator.component.spec.ts
- projects/ion/src/lib/indicator/indicator.component.ts
- stories/Indicator.stories.ts
fix #1020 
fix #1019 
It was added the icon to appear conditionaly when you pass the config, and was added a tooltip to show the title in the cases where the title becomes partialy hidden.
yarn test indicator
https://github.com/Brisanet/ion/assets/138060158/d0835ec0-95d7-4a8d-9296-733d8ccdd3f7
[Long title story](https://62eab350a45bdb0a5818520e-jrdbgeljpq.chromatic.com/?path=/story/ion-data-display-indicator--with-long-title)
[With header title icon](https://62eab350a45bdb0a5818520e-jrdbgeljpq.chromatic.com/?path=/story/ion-data-display-indicator--with-title-icon)
> 1019 feat add a tooltip to indicator titles when necessary and header title icon

- projects/ion/src/lib/modal/component/modal.component.ts
- projects/ion/src/lib/modal/modal.service.spec.ts
- projects/ion/src/lib/modal/modal.service.ts
- projects/ion/src/lib/modal/models/modal.interface.ts
- projects/ion/src/lib/utils/datePicker.spec.ts
- projects/ion/src/lib/utils/generateID.spec.ts
- projects/ion/src/lib/utils/generateID.ts
#865
Previously, the modal service allowed only one reference, resulting in the replacement of the first modal when opening a second one. Now, with the refactoring, the service operates with an array of modals, preserving individual references. This prevents conflicts, enabling the simultaneous opening of multiple modals without losing control over each one. The update makes the service more flexible and adaptable to scenarios with multiple modals.
[Gravação de tela de 2024-01-23 11-31-19.webm](https://github.com/Brisanet/ion/assets/138057813/d470890b-0b80-4693-b7fe-0baa5e7553e7)
> fix: modal service close #865

- projects/ion/src/lib/popover/popover.directive.spec.ts
- projects/ion/src/lib/popover/popover.directive.ts
- stories/Popover.stories.ts
#1023
fix: don't close popover when scroll event in popover body
[Gravação de tela de 2024-02-09 13-49-24.webm](https://github.com/Brisanet/ion/assets/138057813/fe5962f9-eea6-467b-845e-ef12c37a9b1c)
> fix: scroll close popover #1023

- projects/ion/src/lib/modal/component/modal.component.html
- projects/ion/src/lib/modal/component/modal.component.spec.ts
> fix: remove border radius of ion-alert in modal #1026

- projects/ion/src/lib/breadcrumb/breadcrumb.component.html
- projects/ion/src/lib/breadcrumb/breadcrumb.component.scss
- projects/ion/src/lib/breadcrumb/breadcrumb.component.spec.ts
- projects/ion/src/lib/breadcrumb/breadcrumb.component.ts
- projects/ion/src/lib/breadcrumb/breadcrumb.module.ts
- projects/ion/src/lib/breadcrumb/mock/breadcrumb-truncated.component.ts
- projects/ion/src/lib/core/types/breadcrumb.ts
- stories/Breadcrumb.stories.ts
This feature aims to enhance the breadcrumbs functionality by introducing a truncation mechanism. When navigating through a deep hierarchy of pages, breadcrumbs can become excessively long, causing layout issues and decreasing usability. Therefore, this feature will provide the ability to truncate the breadcrumbs display while still maintaining navigational context.
https://github.com/Brisanet/ion/assets/138119077/ca7f97be-2d42-43c0-9a40-f4ba23327c0a
https://62eab350a45bdb0a5818520e-bajwoiopcg.chromatic.com/?path=/story/ion-navigation-breadcrumb--with-truncation
> feat: create truncation in breadcrumbs

- projects/ion/src/lib/triple-toggle/triple-toggle.component.spec.ts
- projects/ion/src/lib/triple-toggle/triple-toggle.component.ts
Currently, the triple-toggle component includes constants storing default values used for visual validation. Consequently, when two or more triple-toggle components are rendered on the same screen, the selected value is changed in all references. The issue has been addressed with a correction.
> refactor: adjust the default reference of the triple-toggle component

- projects/ion/src/lib/modal/component/modal.component.html
- projects/ion/src/lib/modal/component/modal.component.spec.ts
- projects/ion/src/lib/modal/mock/open-modal.mock.component.ts
- projects/ion/src/lib/modal/modal.service.spec.ts
- projects/ion/src/lib/modal/modal.service.ts
- projects/ion/src/lib/modal/models/modal.interface.ts
fix #1041 
fix #1040 
It was added a property "preventCloseOnConfirm" so it wont close at primary action and a property "customClass" to provide more css flexibility, to the modal configuration.
> feat: modal prevent close on confirm and custom class

- projects/ion/src/lib/core/types/index.ts
- projects/ion/src/lib/core/types/steps.ts
- projects/ion/src/lib/step/step.component.html
- projects/ion/src/lib/step/step.component.scss
- projects/ion/src/lib/step/step.component.spec.ts
- projects/ion/src/lib/step/step.component.ts
- projects/ion/src/lib/step/step.module.ts
- projects/ion/src/lib/utils/pipes/ellipsis/ellipses.pipe.spec.ts
- projects/ion/src/lib/utils/pipes/ellipsis/ellipsis.pipe.ts
- projects/ion/src/lib/utils/pipes/ellipsis/index.ts
- projects/ion/src/lib/utils/pipes/pipes.module.ts
- stories/Step.stories.ts
#1044 
- Creating a vertical variant to ion-steps
- Adding "preventStepChange" to don't change automatically when click (usefull in cases that we need to do some validations before change step)
- Exporting step types and remove unused types
| source | screenshot |
| --- | --- |
| yoda | <img height="350" src="https://github.com/Brisanet/ion/assets/138119077/9127356f-244c-47cd-ab81-0cd475ed66ea" />|
| storybook | <img height="350" src="https://github.com/Brisanet/ion/assets/138119077/14cb3225-197a-4678-b926-2f51b2c35b38" /> |
https://62eab350a45bdb0a5818520e-nhasrpmivp.chromatic.com/?path=/story/ion-navigation-steps--vertical
the functionality was also validated in the Caná system to ensure that this change did not affect existing projects
> feat: adding vertical variant to ion-steps (#1044)

- projects/ion/src/lib/link/link.component.html
- projects/ion/src/lib/link/link.component.scss
- projects/ion/src/lib/link/link.component.spec.ts
fix #1068 
The disabled atribute was removed and the disabled validation and properties were moved to an class selector.
> fix: ion link disabled atribute

- projects/ion/src/lib/popover/component/popover.component.html
- projects/ion/src/lib/popover/component/popover.component.scss
- projects/ion/src/lib/popover/component/popover.component.spec.ts
- stories/Popover.stories.ts
fix #1037 
Now when user doesnt provide a title to the popover it renders without the header and with a customized style.
- Popover without the header;
- Scrollbar style fixed.
> feat: popover without header

- projects/ion/src/lib/core/types/indicator.ts
- projects/ion/src/lib/core/types/popover.ts
- projects/ion/src/lib/indicator/indicator.component.html
- projects/ion/src/lib/popover/popover.directive.spec.ts
- projects/ion/src/lib/popover/popover.directive.ts
fix #1081 
It was added a new Input property "ionPopoverStopCloseOnScroll" to the ion Popover, so user is able to tell if it should not close when scrolling. The indicator was also updated, beeing added the property there.
> 1081 feat prevent popover close on scroll

- projects/ion/src/lib/indicator/indicator.component.html
- projects/ion/src/lib/indicator/indicator.component.spec.ts
fix #1083 
When the button config is informed it always renders the button, even if the value provided is invalid, so I added a validation so it wont render the footer if the value informed is invalid.
- Added a validation to the footer, checking the validity of the value provided;
- tests updated.
> fix: footer visibility in indicator with invalid value

- projects/ion/src/lib/core/types/datepicker.ts
- projects/ion/src/lib/picker/core/calendar-model.ts
- projects/ion/src/lib/picker/core/day.ts
- projects/ion/src/lib/picker/date-picker/date-picker-calendar/date-picker-calendar.component.html
- projects/ion/src/lib/picker/date-picker/date-picker-calendar/date-picker-calendar.component.scss
- projects/ion/src/lib/picker/date-picker/date-picker-calendar/date-picker-calendar.component.spec.ts
- projects/ion/src/lib/picker/date-picker/date-picker-calendar/date-picker-calendar.component.ts
- projects/ion/src/lib/picker/date-picker/date-picker.component.html
- projects/ion/src/lib/picker/date-picker/date-picker.component.scss
- projects/ion/src/lib/picker/date-picker/date-picker.component.spec.ts
- projects/ion/src/lib/picker/date-picker/date-picker.component.ts
- stories/Datepicker.stories.ts
fix #1086 
User now can disable dates based on a rule that can be specified in a function to be passed to the date-picker component. This function has a "currentDate" parameter that represents the day that is beeing compared to return a boolean resulting from a check if either it will be disabled or not.
The position that the calendar was beeing reendered was also fixed, given user now 4 options of positioning.
[Story](https://62eab350a45bdb0a5818520e-nschehsddo.chromatic.com/?path=/story/ion-data-entry-datepicker--with-disabled-date)
> 1086 feat disabled date range on date picker

- projects/ion/src/lib/core/types/popconfirm.ts
- projects/ion/src/lib/popconfirm/mock/open-popconfirm.component.ts
- projects/ion/src/lib/popconfirm/popconfirm.directive.spec.ts
- projects/ion/src/lib/popconfirm/popconfirm.directive.ts
fix #1091 
It was required from the popconfirm to close on scroll, so it was added a listener and a input property to only close when it is informed.
yarn test popconfirm.directive
> feat: popconfirm close on scroll

- projects/ion/src/lib/input-select/input-select.component.html
Prevents that the select is opened or closed when enter is pressed when ion-input-select is inside a form.
> fix: input select opening options when enter is pressed inside a form

- projects/ion/src/lib/smart-table/smart-table.component.html
- projects/ion/src/lib/smart-table/smart-table.component.spec.ts
- projects/ion/src/lib/table/utilsTable.ts
After this implementation, empty tags and empty links will look like this:
I also fixed a bug where, when on config table we declare explicitly that type is 'text', nothing was displayed.
> feat: empty cell on tag and link show config

- projects/ion/src/lib/core/types/input-counter.ts
- projects/ion/src/lib/input-counter/input-counter.component.html
- projects/ion/src/lib/input-counter/input-counter.component.scss
- projects/ion/src/lib/input-counter/input-counter.component.spec.ts
- projects/ion/src/lib/input-counter/input-counter.component.ts
- stories/InputCounter.stories.ts
Adds the min, max and disabled functionalities to the InputCounter component to resolve issue #1153 
- Modified the InputCounter component to accept and handle min, max, and disabled props.
- Added validation logic to restrict input values based on the min and max props.
- Updated the rendering logic to disable the input when the disabled prop is set.
> fix: add min max and disabled props to input counter

- projects/ion/src/lib/core/types/notification.ts
- projects/ion/src/lib/notification/service/notification.container.component.ts
- projects/ion/src/lib/notification/service/notification.service.spec.ts
- projects/ion/src/lib/notification/service/notification.service.ts
fix #1188 
It was required for the notification service to have a limit on the stack of notifications.
- Added a config property to the service;
- added a control array and a validation to the notification container, so it will close the first notification if the control array is at its max length.
> feat: add notifications limit option

- projects/ion/src/lib/button/button.component.html
- projects/ion/src/lib/button/button.component.spec.ts
- stories/Button.stories.mdx
#1183  
prevents this behavior:
https://62eab350a45bdb0a5818520e-ixytjedbow.chromatic.com/?path=/story/ion-navigation-button--with-dropdown-circular-button-with-multiple-choices
> style: not showing badge when dropdown is multiple and button is circular

- projects/ion/src/lib/badge/_badge.theme.scss
- projects/ion/src/lib/badge/badge.component.scss
- projects/ion/src/lib/badge/badge.component.spec.ts
- projects/ion/src/lib/core/types/badge.ts
> feat: add warning in badge #1208

- projects/ion/src/lib/core/types/tour.ts
- projects/ion/src/lib/tour/mocks/resizing-host-demo.component.ts
- projects/ion/src/lib/tour/mocks/tour-basic-demo.component.ts
- projects/ion/src/lib/tour/tour-backdrop/tour-backdrop.component.spec.ts
- projects/ion/src/lib/tour/tour-backdrop/tour-backdrop.component.ts
- projects/ion/src/lib/tour/tour-step.directive.spec.ts
- projects/ion/src/lib/tour/tour-step.directive.ts
- projects/ion/src/lib/tour/tour.service.spec.ts
- projects/ion/src/lib/tour/tour.service.ts
- stories/TourDocs.stories.mdx
- stories/TourResizing.stories.ts
#1221
[Storybook](https://62eab350a45bdb0a5818520e-twpcivyupl.chromatic.com/?path=/story/ion-data-display-tour--basic-tour)
> fix: ensure the component fully renders before proceeding to the next step in ionTour

- .github/workflows/main.yml
- .github/workflows/prod.yml
**Description**
This pull request migrates our CI workflow for code coverage reporting from the deprecated Code Climate platform to the new, official Qlty Cloud service.
**Context**
The original Code Climate Quality platform is being shut down and replaced by a completely rebuilt service called Qlty. As a result, the `paambaati/codeclimate-action` we were using is now obsolete and points to a service that will no longer be maintained. This migration is necessary to ensure our code coverage reporting continues to function correctly.
**Summary of Changes**
- Replaced the community-maintained `paambaati/codeclimate-action` with the official `qltysh/qlty-action/coverage@v1` action.
- Updated the authentication method from the `CC_TEST_REPORTER_ID` environment variable to the new token input, …
> ci: update Code Coverage Action for Qlty

- projects/ion/src/lib/core/types/tag.ts
- projects/ion/src/lib/tag/tag.component.html
- projects/ion/src/lib/tag/tag.component.spec.ts
- projects/ion/src/lib/tag/tag.component.ts
- stories/Tag.stories.mdx
#1249 
feat #1249 
Adding background input to the tag
> feat: add background input to the tag #1249

- README.md
- projects/ion/src/lib/input-counter/_input-counter.theme.scss
- projects/ion/src/lib/sidebar/sidebar.component.scss
- projects/ion/src/lib/tag/_tag.theme.scss
- projects/ion/src/lib/tag/tag.component.scss
feat #1248 
adding dark theme in ion-tag
- added _tag.theme.scss file
- modified tag.component.scss file
> feat: adding dark theme to the tag #1248
